### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by 11mLLM** [11mLLM/11mLLM#1]
## Tasks
- [x]  Prompt Engineering Guide 서문
- [x]  LLM Settings
- [x]  Basic of Prompting 
- [x]  Prompt Elements 
- [x]  General Tips for Designing Prompts 
- [x]  Examples of Prompts

**Comment by sunday-sketching** [comment]
@11mLLM 제가 이번주 작업 시작이 좀 늦어서 지금 어사인을 하려고 봤는데 어사인할 수 있는 버튼이 없는데, 이미 이슈 상태가 진행 중이라 그런 거겠죠...?

**Comment by jiwonaid** [comment]
@sunday-sketching 붙여두었습니다!

**Comment by jiwonaid** [comment]
권한이 빠져있으실 수도 있겠네요.

<img width="571" alt="스크린샷 2023-07-22 오후 9 12 06" src="https://github.com/11mLLM/11mLLM/assets/26996017/4e34be8c-400a-49d9-8397-49eaa3c75727">

**Comment by 11mLLM** [comment]
리뷰 1차 완료 ✅
