### ISSUE TITLE
Techniques

### ISSUE THREAD

**Issue by 11mLLM** [11mLLM/11mLLM#2]
## Task
- [ ]  Zero-shot Prompting
- [ ]  Few-shot Prompting
- [ ]  Chain-of-Thought Prompting
- [ ]  Self-Consistency
- [ ]  Generate Knowledge Prompting
- [ ]  Tree of Thoughts
- [ ]  Retrieval Augmented Generation
- [ ]  Automatic Reasoning and Tool-use
- [ ]  Automatic Prompt Engineer
- [ ]  Active-Prompt
- [ ]  Directional Stimulus Prompting
- [ ]  ReAct
- [ ]  Multimodal CoT
- [ ]  Graph Prompting

**Comment by 11mLLM** [comment]
리뷰 1차 완료 ✅
